export interface RedditResponse {
    kind: string;
    data: {
      modhash: string | null;
      dist: number;
      children: {
        kind: string;
        data: {
          approved_at_utc: number | null;
          subreddit: string;
          selftext: string;
          author_fullname: string;
          saved: boolean;
          mod_reason_title: string | null;
          gilded: number;
          clicked: boolean;
          title: string;
          link_flair_richtext: {
            e: string;
            t: string;
          }[];
          subreddit_name_prefixed: string;
          hidden: boolean;
          pwls: number;
          link_flair_css_class: string | null;
          downs: number;
          thumbnail_height: number | null;
          top_awarded_type: string | null;
          parent_whitelist_status: string;
          hide_score: boolean;
          name: string;
          quarantine: boolean;
          link_flair_text_color: string;
          upvote_ratio: number;
          author_flair_background_color: string | null;
          subreddit_type: string;
          ups: number;
          total_awards_received: number;
          media_embed: Record<string, unknown>;
          thumbnail_width: number | null;
          author_flair_template_id: string | null;
          is_original_content: boolean;
          user_reports: string[];
          secure_media: Record<string, unknown> | null;
          is_reddit_media_domain: boolean;
          category: string | null;
          secure_media_embed: Record<string, unknown>;
          link_flair_text: string | null;
          can_mod_post: boolean;
          score: number;
          approved_by: string | null;
          author_premium: boolean;
          thumbnail: string;
          edited: boolean;
          author_flair_css_class: string | null;
          author_flair_richtext: {
            e: string;
            t: string;
          }[];
          gildings: Record<string, number>;
          content_categories: string | null;
          is_self: boolean;
          mod_note: string | null;
          created: number;
          link_flair_type: string;
          wls: number;
          removed_by_category: string | null;
          banned_by: string | null;
          author_flair_type: string;
          domain: string;
          allow_live_comments: boolean;
          selftext_html: string | null;
          likes: boolean | null;
          suggested_sort: string | null;
          banned_at_utc: number | null;
          view_count: number | null;
          archived: boolean;
          no_follow: boolean;
          is_crosspostable: boolean;
          pinned: boolean;
          over_18: boolean;
          all_awardings: Record<string, unknown>[];
          awarders: string[];
          media_only: boolean;
          can_gild: boolean;
          spoiler: boolean;
          locked: boolean;
          author_flair_text: string | null;
          treatment_tags: string[];
          visited: boolean;
          removed_by: string | null;
          num_reports: number | null;
          distinguished: string | null;
          subreddit_id: string;
        };
      }[];
    };
  }